"""Add extra_data to competitors

Revision ID: a90d2357a441
Revises: 001
Create Date: 2025-12-15 01:43:51.722336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a90d2357a441'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.drop_index('ix_competitors_domain', table_name='competitors')
    op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
    op.create_unique_constraint(None, 'competitors', ['domain'])
    op.drop_column('competitors', 'metadata')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.add_column('competitors', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'competitors', type_='unique')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.create_index('ix_competitors_domain', 'competitors', ['domain'], unique=False)
    op.drop_column('competitors', 'extra_data')
    # ### end Alembic commands ###
